name: Deploy to shuttle
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: shuttle-hq/deploy-action@v0.0.3
        with:
          deploy-key: ${{ secrets.shuttleApiKey }}
